name: CI
on: 
  push:
  pull_request:
  workflow_dispatch:
defaults:
  run:
    working-directory: ./Software
jobs:
  build-win:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: choco install --no-progress openssl
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          cache-key-prefix: install-qt-action-default
          version: 6.*
          target: desktop
          arch: win64_msvc2022_64
          modules: qtserialport
          extra: --timeout 60
      - name: Cached Bass
        id: cache-bass
        uses: actions/cache@v4
        with:
          path: C:\bass
          key: ${{ runner.os }}-bass_24
      - name: Install Bass
        if: steps.cache-bass.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          If (!(Test-Path -Path "C:\bass" )) {
            (New-Object System.Net.WebClient).DownloadFile("https://un4seen.com/files/bass24.zip", "C:\bass.zip")
            (New-Object System.Net.WebClient).DownloadFile("https://un4seen.com/files/basswasapi24.zip", "C:\basswasapi.zip")
            Expand-Archive C:\bass.zip -DestinationPath C:\bass
            Expand-Archive C:\basswasapi.zip -DestinationPath C:\bass\wasapi
          }
      - name: Cached NightLight
        id: cache-nightlight
        uses: actions/cache@v4
        with:
          path: C:\NightLight
          key: ${{ runner.os }}-nightlight_1.3_1909
      - name: Install NightLight
        if: steps.cache-nightlight.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          If (!(Test-Path -Path "C:\NightLight" )) {
            (New-Object System.Net.WebClient).DownloadFile("https://github.com/zomfg/NightLightLibrary/releases/download/v1.3/NightLightLibrary-x64-1.3-win1909preview.zip", "C:\NightLight.zip")
            Expand-Archive C:\NightLight.zip -DestinationPath C:\NightLight
          }
      - name: Set build vars
        shell: bash
        run: |
          echo "OPENSSL_DIR = \"C:\\Program Files\\OpenSSL\\bin\"" > build-vars.prf
          echo "DEFINES += BASS_SOUND_SUPPORT" >> build-vars.prf
          echo "BASS_DIR = \"C:\\bass\"" >> build-vars.prf
          echo "BASSWASAPI_DIR = \"C:\\bass\\wasapi\"" >> build-vars.prf
          echo "DEFINES += NIGHTLIGHT_SUPPORT" >> build-vars.prf
          echo "NIGHTLIGHT_DIR = \"C:\\NightLight\"" >> build-vars.prf
          echo "TARGET_ARCH = x86_64" >> build-vars.prf
      - name: Build
        shell: cmd
        run: |
          set QTDIR=%QT_ROOT_DIR%
          call scripts\win32\generate_sln.bat
          MSBuild.exe Lightpack.sln /p:Configuration=Release
      - name: Prepare Installer
        shell: bash
        run: |
          scripts/win32/prepare_installer.sh
      - name: Build Installer
        shell: cmd
        run: |
          "C:/Program Files (x86)/Inno Setup 6/ISCC.exe" script_qt6.iss
        working-directory: ./Software/dist_windows
      - name: Check Package
        shell: bash
        run: |
          set -xe
          PKG_PATH=$(ls dist_windows/Output/Prismatik*.exe)
          PKG_NAME=$(basename "$PKG_PATH")
          echo "PKG_PATH=Software/$PKG_PATH" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_PATH }}
  build-flatpack:
    runs-on: ubuntu-24.04
    name: Flatpack Build
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Flatpak
        run: |
          set -xe
          sudo apt update
          sudo apt install flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - name: Build
        working-directory: Software/dist_linux
        run: ./build-natively.sh flatpak
      - name: Check Package
        run: |
          set -xe
          PKG_PATH=$(ls dist_linux/flatpak/prismatik*.flatpak)
          echo "PKG_PATH=Software/$PKG_PATH" >> $GITHUB_ENV
          echo "PKG_NAME=$(basename $PKG_PATH)" >> $GITHUB_ENV
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}
          path: ${{ env.PKG_PATH }}
